config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :galleries, only: [:index, :show]

  namespace :users do
    resources :users, only: [:show] do
      resources :galleries do
        resources :gallery_images, except: [:index, :show]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	# Associations
	belongs_to :user
	has_many :gallery_images, dependent: :destroy

	# Validations
	validates :name, presence: true
end

app/models/gallery_image.rb
class GalleryImage < ApplicationRecord
	belongs_to :gallery

	has_one_attached :image

	delegate :user, to: :gallery
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable, :validatable
  devise :database_authenticatable, :registerable, :rememberable

  # Associaitons
  has_many :galleries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(user)
		users_user_path(user)
	end
end

app/controllers/galleries_controller.rb
class  GalleriesController < ApplicationController
	def index
		@galleries = Gallery.all
	end
end

app/controllers/home_controller.rb
class  HomeController < ApplicationController
	def index
	end
end

app/controllers/users/galleries_controller.rb
module Users
  class GalleriesController < UsersController
		before_action :set_gallery, only: [:edit, :update, :destroy, :show]

		def index
			@galleries = current_user.galleries
		end

		def show
		end

		def new
			@gallery = Gallery.new
		end

		def edit
		end

		def create
			@gallery = Gallery.new(gallery_params)
			@gallery.user = current_user
			if @gallery.save
				flash[:notice] = t('.gallery_created')
				redirect_to users_user_galleries_path(current_user)
			else
				render :new
			end
		end

		def update
			if @gallery.update(gallery_params)
				flash[:notice] = t('.gallery_updated')
				redirect_to users_user_galleries_path(current_user)
			else
				render :edit
			end
		end

		def destroy
			flash[:notice] = if @gallery.destroy
				 t('.gallery_deleted')
			else
				t('.failed_gallery_delete')
			end
			redirect_to users_user_galleries_path(current_user)
		end

		private

		def user_id
			params[:user_id]
		end

		def gallery_id
			params[:id]
		end

		def set_gallery
			@gallery = Gallery.find_by(id: gallery_id)
			head 404 unless @gallery.present? && @gallery.user == current_user
		end

		def gallery_params
			params.require(:gallery).permit(:name)
		end
  end
end

app/controllers/users/gallery_images_controller.rb
module Users
  class GalleryImagesController < GalleriesController
		before_action :set_gallery
		before_action :set_gallery_image, only: [:edit, :update, :destroy]

		def new
			@image = GalleryImage.new
		end

		def edit
		end

		def create
			@image = GalleryImage.new(gallery_image_params)
			@image.gallery = @gallery
			if @image.save
				flash[:notice] = t('.image_created')
				redirect_to users_user_gallery_path(current_user, @gallery)
			else
				render :new
			end
		end

		def update
			if @image.update(gallery_image_params)
				flash[:notice] = t('.image_updated')
				redirect_to users_user_gallery_path(current_user, @gallery)
			else
				render :edit
			end
		end

		def destroy
			flash[:notice] = if @image.destroy
				 t('.image_deleted')
			else
				t('.failed_image_delete')
			end
			redirect_to users_user_gallery_path(current_user, @gallery)
		end

		private

		def user_id
			params[:user_id]
		end

		def gallery_id
			params[:gallery_id]
		end

		def gallery_image_id
			params[:id]
		end

		def set_gallery_image
			@image = GalleryImage.find_by(id: gallery_image_id)
			head 404 unless @image.present? && @image.gallery == @gallery
		end

		def gallery_image_params
			params.require(:gallery_image).permit(:title, :alt, :image)
		end
  end
end

app/controllers/users/users_controller.rb
module Users
  class UsersController < ApplicationController
		before_action :authenticate_user!
		before_action :validate_user

		def show
		end

		private

		def user_id
			params[:id]
		end

		def validate_user
			user = User.find_by(id: user_id)
			head 401 unless user.present? && user == current_user
		end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/_gallery.html.erb
<div class="card">
    <div class="card-header">
        <p class="card-header-title">
            <%= gallery.name %>
        </p>
    </div>
</div>

app/views/galleries/index.html.erb
<section class="section">
    <div class="container">
        <% @galleries.each do |gallery| %>
            <%= render partial: 'gallery', locals: {gallery: gallery} %>
        <% end %>
    </div>
</section>

app/views/home/index.html.erb
<section class="hero is-info">
    <div class="hero-body">
        <p class="title">View and create Galleries</p>
        <a class="button" href="<%= galleries_path %>">View galleries</a>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageGalleryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar is-transparent">
    <div class="navbar-brand p-4">
        <a class="navbar-item title is-3" href="<%= root_path %>">Gallery App</a>
        <% if user_signed_in? %>
            <%= link_to t(".logout"), destroy_user_session_path, method: :delete, class: "navbar-item button" %>
        <% else %>
            <%= link_to t(".sign_in"), new_user_session_path, class: "navbar-item button" %>
            <%= link_to t(".register"), new_user_registration_path, class: "navbar-item button" %>
        <% end %>
    </a>
</div>

app/views/users/galleries/_form.html.erb
<%= form_with model: [:users, current_user, gallery] do |form|%>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.submit %>
<% end %>

app/views/users/galleries/_gallery.html.erb
<div class="card">
    <div class="card-header">
        <p class="card-header-title">
            <%= gallery.name %>
        </p>
    </div>

    <div class="card-footer">
        <%= link_to t(".view_gallery"), users_user_gallery_path(gallery.user, gallery), class: "card-footer-item" %>
        <%= link_to t(".edit_gallery"), edit_users_user_gallery_path(gallery.user, gallery), class: "card-footer-item" %>
        <%= link_to t(".delete_gallery"), users_user_gallery_path(gallery.user, gallery), method: :delete, class: "card-footer-item" %>
    </div>
</div>

app/views/users/galleries/edit.html.erb
<%= render partial: 'form', locals: {gallery: @gallery} %>

app/views/users/galleries/index.html.erb
<section class="section">
    <%= link_to t(".new_gallery"), new_users_user_gallery_path(current_user), class: "button" %>
    <div class="container">
        <% @galleries.each do |gallery| %>
            <%= render partial: 'gallery', locals: {gallery: gallery} %>
        <% end %>
    </div>
</section>

app/views/users/galleries/new.html.erb
<%= render partial: 'form', locals: {gallery: @gallery} %>

app/views/users/galleries/show.html.erb
<section class="section">
    <%= link_to t(".new_image"), new_users_user_gallery_gallery_image_path(current_user, @gallery), class: "button" %>
    <div class="container">
        <% @gallery.gallery_images.each do |image| %>
            <%= render partial: 'users/gallery_images/image', locals: {image: image} %>
        <% end %>
    </div>
</section>

app/views/users/gallery_images/_form.html.erb
<%= form_with model: [:users, current_user, @gallery, image] do |form|%>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :alt %>
    <%= form.text_field :alt %>

    <%= form.label :image %>
    <%= form.file_field :image %>

    <%= form.submit %>
<% end %>

app/views/users/gallery_images/_image.html.erb
<div class="card">
    <div class="card-image">
       <%= image_tag  image.image.variant(resize_to_limit: [100, 100]) %>
    </div>

    <div class="card-footer">
        <%= link_to t(".edit_image"), edit_users_user_gallery_gallery_image_path(image.user, image.gallery, image), class: "card-footer-item" %>
        <%= link_to t(".delete_image"), users_user_gallery_gallery_image_path(image.user, image.gallery, image), method: :delete, class: "card-footer-item" %>
    </div>
</div>

app/views/users/gallery_images/edit.html.erb
<%= render partial: 'form', locals: {image: @image} %>

app/views/users/gallery_images/new.html.erb
<%= render partial: 'form', locals: {image: @image} %>

app/views/users/users/show.html.erb
<%= link_to t(".view_my_galleries"), users_user_galleries_path(current_user), class: "button" %>